### ISSUE TITLE
⚠  warning   WARNING: "headers" is missing.

### ISSUE THREAD

**Issue by GENESIS-PLUS** [DaggieBlanqx/whatsappcloudapi_wrapper#12]
The terminal constantly throws an error when calling function: 
```
await Whatsapp.sendText({
        message: body,
        recipientPhone: recipientPhone,
 });
```

⚠  warning   WARNING: "headers" is missing.

**Comment by sumonst21** [comment]
@GENESIS-PLUS Update express version

**Comment by Bintang73** [comment]
just edit the code lib on index.js

`if (!headers && !defaultHeaders()) {
                    signale.warn(`WARNING: "headers" is missing.`);
}`
