### ISSUE TITLE
sendAudio has wrong parameters

### ISSUE THREAD

**Issue by Lilleri** [DaggieBlanqx/whatsappcloudapi_wrapper#5]
the sendAudio function set wrong parameters, according to whatsapp business cloud api
the audio must not have an caption parameters,
if you set the param, it will return this error:
[{"status":"failed","message":"(#100) Unexpected key \"caption\" on param \"audio\".","type":"OAuthException","code":100,"fbtrace_id":"doe"}]

**Comment by haziqmus** [comment]
same problem here.

**Comment by DaggieBlanqx** [comment]
This has been addressed.
